### ISSUE TITLE
NPM to be built

### ISSUE THREAD

**Issue by MaXwellFalstein** [MaXwellFalstein/Parallel2.js#1]
I will be working on the NPM feature for Parallel2.js during the week commencing 18th July 2016.

It will be live an running by 30th July 2016 depending on my availability during the next two weeks.

**Comment by MaXwellFalstein** [comment]
I will be building the NPM package this week. I will be starting on Tuesday 26th July 2016; I hope to have all of the bugs and issues, only relating to the NPM package, resolved by Sunday 30th July 2016.

**Comment by amilajack** [comment]
Sorry for the delay of the work on my branch. I'll start working on it in a few days or so. I'm being held back by some other projects

**Comment by MaXwellFalstein** [comment]
No problem. We are all very busy, so development will take its time and we will see when we can push releases in the not too distant future.
