### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by amilajack** [MaXwellFalstein/Parallel2.js#2]
@MaXwellFalstein I think it would be better if we renamed the module to `paralleljs2`. The clearer similarity between the names would make it more clear that this is the next version of 'the paralleljs' if that makes sense.

**Comment by amilajack** [comment]
Never mind actually. I think this should be fine.

**Comment by MaXwellFalstein** [comment]
I took some time to think about the naming whilst at work today.

I like Parallel.js with the ending .js. It looks great to me. I agree with Parallel.js2 would be good for people, but it would be an issue for the .js ending for me. It looks like .js2 is version two of JavaScript.

I thought Parallel2.js would be the best choice.

**Comment by amilajack** [comment]
Yea I agree

**Comment by amilajack** [comment]
Also please enable the travis and appveyor tests for this repo. I'm about to push the support for them

**Comment by MaXwellFalstein** [comment]
I will do that now :)
