### ISSUE TITLE
Contributor information

### ISSUE THREAD

**Issue by amilajack** [MaXwellFalstein/Parallel2.js#3]
@MaXwellFalstein I need your contributor information, including your domain an email address. I have to add these to the package.json contributors section.

**Comment by MaXwellFalstein** [comment]
I will add it now :)

**Comment by amilajack** [comment]
Make sure you add it in the dev-master branch

**Comment by MaXwellFalstein** [comment]
I will do.

**Comment by MaXwellFalstein** [comment]
Added contributor info and added some keywords.
