### ISSUE TITLE
First Timers Only - Example Web Sites

### ISSUE THREAD

**Issue by MaXwellFalstein** [MaXwellFalstein/Parallel2.js#8]
Any First Timers allowed, the First-Timers-Only branch will be for first timers only.

This does not mean we will not accept experienced coders and maintainers with pull requests ready to go.

The FTs will be given the opportunity to learn how to use GitHub whilst being walked through development using this GitHub repository.

We will show you how to build the web sites with Parallel2.js to gain an understanding of how Parallel2.js works.

After your first successful pull request, you are welcome to stay around for the main event, where you can raise issues for what you would like to be done and how you would like to do it or see it being done.

**Comment by RakshithNM** [comment]
Hey, I would like to work on this. Please guide me.

**Comment by amilajack** [comment]
This project isn't (or should be) active anymore. @RakshithNM If you would like to contribute, please contribute to the https://github.com/parallel-js/parallel.js repo
