### ISSUE TITLE
Parallel.js renamed to Parallel2.js

### ISSUE THREAD

**Issue by MaXwellFalstein** [MaXwellFalstein/Parallel2.js#9]
Should we rename Parallel.js to Parallel2.js?

We would have a to do a little bit or sorting within the other files, but it should be okay to do.

**Comment by amilajack** [comment]
The ownership of the original paralleljs library changed to an organization. I invited you to it.

https://github.com/parallel-js/parallel.js

**Comment by MaXwellFalstein** [comment]
Fantastic!
